# Generated by Django 3.2.5 on 2021-09-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210830_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='contactnumber',
            new_name='Contactnumber',
        ),
        migrations.AlterField(
            model_name='products',
            name='Product_name',
            field=models.CharField(max_length=100),
        ),
    ]
