# Generated by Django 3.2.5 on 2021-09-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
