# Generated by Django 3.2.5 on 2021-09-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=20)),
                ('Contactnumber', models.BigIntegerField()),
                ('Emailid', models.CharField(max_length=100)),
                ('Shippingaddress', models.CharField(max_length=400)),
                ('Nearbylandmark', models.CharField(max_length=40)),
            ],
        ),
    ]
